=== cms-externals/tkonlinesw/FecSoftwareV3_0/config/conversionSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'>

 <xsd:element name="ROWSET">
  <xsd:complexType>
   <xsd:sequence>
     <xsd:element ref="DCUCONVERSION" minOccurs='0' maxOccurs='unbounded'/>
     <xsd:element ref="DCUINFO" minOccurs='0' maxOccurs='unbounded'/>
     <xsd:element ref="RAWIDVSHOSTNAME" minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>
  </xsd:complexType>
</xsd:element>

 <xsd:element name="DCUCONVERSION">
  <xsd:complexType>
   <xsd:attribute name="dcuHardId" type="xsd:unsignedLong" />
   <xsd:attribute name="subDetector" type="xsd:string" />
   <xsd:attribute name="dcuType" type="xsd:string" />
   <xsd:attribute name="structureId" type="xsd:string" />
   <xsd:attribute name="containerId" type="xsd:string" />
   <xsd:attribute name="detId" type="xsd:unsignedLong" />
   <xsd:attribute name="adcGain0" type="xsd:double" />
   <xsd:attribute name="adcOffset0" type="xsd:double" />
   <xsd:attribute name="adcInl0" type="xsd:double" />
   <xsd:attribute name="adcInl0OW" type="xsd:string" />
   <xsd:attribute name="adcCal0" type="xsd:string" />
   <xsd:attribute name="i20" type="xsd:double" />
   <xsd:attribute name="i10" type="xsd:double" />
   <xsd:attribute name="iCal" type="xsd:string" />
   <xsd:attribute name="kDiv" type="xsd:double" />
   <xsd:attribute name="kCal" type="xsd:string" />
   <xsd:attribute name="tsGain" type="xsd:double" />
   <xsd:attribute name="tsOffset" type="xsd:double" />
   <xsd:attribute name="tsCal" type="xsd:string" />
   <xsd:attribute name="r68" type="xsd:double" />
   <xsd:attribute name="r68Cal" type="xsd:string" />
   <xsd:attribute name="adcGain2" type="xsd:double" />
   <xsd:attribute name="adcOffset2" type="xsd:double" />
   <xsd:attribute name="adcCal2" type="xsd:string" />
   <xsd:attribute name="adcGain3" type="xsd:double" />
   <xsd:attribute name="adcOffset3" type="xsd:double" />
   <xsd:attribute name="adcCal3" type="xsd:string" />
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="DCUINFO">
  <xsd:complexType>
   <xsd:attribute name="dcuHardId" type="xsd:unsignedLong" />
   <xsd:attribute name="detId" type="xsd:unsignedLong" />
   <xsd:attribute name="fibreLength" type="xsd:double" />
   <xsd:attribute name="apvNumber" type="xsd:int" />
   <xsd:attribute name="timeOfFlight" type="xsd:double" />
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="RAWIDVSHOSTNAME">
  <xsd:complexType>
   <xsd:attribute name="SUBDETECTOR" type="xsd:string" />
   <xsd:attribute name="CRATEID" type="xsd:string" />
   <xsd:attribute name="HOSTNAME" type="xsd:string" />
   <xsd:attribute name="SLOT" type="xsd:unsignedLong" />
   <xsd:attribute name="ID" type="xsd:string" />
  </xsd:complexType>
 </xsd:element>



</xsd:schema>

=== cms-externals/tkonlinesw/FecSoftwareV3_0/ThirdParty/DeviceFactoryTemplate/xml/CrackDetId_fakeLengths.xml
<?xml version="1.0"?>
<ROWSET xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='http://cmsdoc.cern.ch/cms/cmt/System_aspects/FecControl/binaries/misc/conversionSchema.xsd'>
	<DCUINFO dcuHardId="3797663" detId="436330533" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="13759165" detId="436314180" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="5894415" detId="436248624" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="5896347" detId="436314156" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="16710717" detId="436215856" fibreLength="1000" apvNumber="6" />
	<DCUINFO dcuHardId="11795783" detId="436248652" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="6157291" detId="436215860" fibreLength="1000" apvNumber="6" />
	<DCUINFO dcuHardId="4128479" detId="436314200" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="5961207" detId="436330545" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="15855933" detId="436314196" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="6025671" detId="436314164" fibreLength="1000" apvNumber="6" />
	<DCUINFO dcuHardId="3538291" detId="436232236" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="7992925" detId="436232248" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="6157303" detId="436330549" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="14284538" detId="436248644" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="4128303" detId="436215888" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="14021487" detId="436215864" fibreLength="1000" apvNumber="6" />
	<DCUINFO dcuHardId="6225447" detId="436314160" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="13762291" detId="436248628" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="14022843" detId="436232244" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="5700879" detId="436232276" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="14023039" detId="436281388" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="3797899" detId="436232260" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="3800603" detId="436314148" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="14546071" detId="436281396" fibreLength="1000" apvNumber="6" />
	<DCUINFO dcuHardId="12449319" detId="436215880" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="15858859" detId="436281380" fibreLength="1000" apvNumber="6" />
	<DCUINFO dcuHardId="5373171" detId="436248664" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="16645531" detId="436330541" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="6028023" detId="436215848" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="12187813" detId="436330536" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="7469547" detId="436314168" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="14610743" detId="436330553" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="5765751" detId="436265012" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="16383067" detId="436297784" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="16382299" detId="436281384" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="3603191" detId="436297780" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="13890671" detId="436232240" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="14154313" detId="436265005" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="11926515" detId="436232268" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="11795675" detId="436215876" fibreLength="1000" apvNumber="6" />
	<DCUINFO dcuHardId="16118875" detId="436297776" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="16382707" detId="436248656" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="5962251" detId="436265001" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="13759647" detId="436264997" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="8319363" detId="436232228" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="3667679" detId="436314184" fibreLength="1000" apvNumber="6" />
	<DCUINFO dcuHardId="5501567" detId="436281392" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="6025755" detId="436215852" fibreLength="1000" apvNumber="6" />
	<DCUINFO dcuHardId="5895483" detId="436265017" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="7599481" detId="436330544" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="13761779" detId="436232272" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="8253946" detId="436248660" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="12320267" detId="436265013" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="5766759" detId="436265008" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="4062187" detId="436215892" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="13759279" detId="436297768" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="14613693" detId="436314192" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="5503323" detId="436281400" fibreLength="1000" apvNumber="6" />
	<DCUINFO dcuHardId="14417029" detId="436330548" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="6025971" detId="436248616" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="7468647" detId="436265000" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="6028295" detId="436297764" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="12451143" detId="436232280" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="11796101" detId="436265016" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="14282907" detId="436215884" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="16184539" detId="436215844" fibreLength="1000" apvNumber="6" />
	<DCUINFO dcuHardId="6026951" detId="436248648" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="4060091" detId="436232232" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="4062215" detId="436248632" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="6025605" detId="436264996" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="8254951" detId="436297772" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="6156659" detId="436265009" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="14546375" detId="436314152" fibreLength="1200" apvNumber="6" />
	<DCUINFO dcuHardId="8321739" detId="436330532" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="14022387" detId="436248620" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="8123927" detId="436215896" fibreLength="1000" apvNumber="6" />
	<DCUINFO dcuHardId="7731365" detId="436265004" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="6224423" detId="436314188" fibreLength="1000" apvNumber="6" />
	<DCUINFO dcuHardId="3800151" detId="436330540" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="3274227" detId="436248612" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="6028531" detId="436232264" fibreLength="1200" apvNumber="4" />
	<DCUINFO dcuHardId="3865201" detId="436330537" fibreLength="1000" apvNumber="4" />
	<DCUINFO dcuHardId="14611063" detId="436330552" fibreLength="1200" apvNumber="4" />
</ROWSET>
